env: prod
loadBalancerIP: 10.0.192.20
internalIP: true
unprivileged: true
image:
  port: 3333
  name: trkmtcrprod2wiacr.azurecr.io/ann-sb-alert-sender/prod # acr image name
replicaCount: 1

requests:
  cpu:
  memory:

limits:
  cpu:
  memory: