env: prod
image:
  name: trkmtcrprod2wiacr.azurecr.io/ann-message-service/prod
  tag: latest

loadBalancerIP: 10.0.64.56
internalIP: true
unprivileged: true
sms:
  requests:
    cpu:
    memory:
  limits:
    cpu:
    memory:

email:
  requests:
    cpu:
    memory:
  limits:
    cpu:
    memory: