appName: tapeevents
environment: us-stress
replicaCount: 5
loadBalancerIP: 172.177.35.171
image:
  name: trkuniusstressacr.azurecr.io/tapeevents
  tag: "latest"
  port: 9002

requests:
  cpu:
  memory:

limits:
  cpu:
  memory: