appName: external
environment: qa
replicaCount: 1
loadBalancerIP: 172.190.184.163
image:
  name: multitenantdev2.azurecr.io/external
  tag: "latest"
  port: 9000

requests:
  cpu:
  memory:

limits:
  cpu:
  memory: