appName: filter
environment: qa
replicaCount: 5
loadBalancerIP: 172.190.184.163
image:
  name: multitenantdev2.azurecr.io/filter
  tag: "latest"
  port: 8098

requests:
  cpu:
  memory:

limits:
  cpu:
  memory: