env: prod
loadBalancerIP: 10.0.64.56
internalIP: true
unprivileged: true
image:
  port: 8080
  targetPort: 8080
  name: trkmtcrprod2wiacr.azurecr.io/ann-rule-engine/prod
replicaCount: 2
requests:
  cpu:
  memory:

limits:
  cpu: 500m
  memory: 1024Mi
