env: prod
loadBalancerIP: 10.0.64.56
internalIP: true
unprivileged: true
image:
  port: 8080
  targetPort: 8080
  name: trkmtcrprod2wiacr.azurecr.io/ann-rule-engine/prod
replicaCount: 4
requests:
  cpu: 1000m
  memory: 2048Mi

limits:
  cpu: 5000m
  memory: 10240Mi
