env: us-stress
loadBalancerIP: 20.114.227.163
image:
  port: 8080
  targetPort: 8080
  name: trkuniusstressacr.azurecr.io/us-stress/ann-rule-engine # acr image name
replicaCount: 3
requests:
  cpu:
  memory:

limits:
  cpu:
  memory: