appName: mobile
environment: manufacturing
replicaCount: 1
loadBalancerIP: 20.172.135.184
image:
  name: multitenantacrprod.azurecr.io/mobile
  tag: "latest"
  port: 9091

requests:
  cpu:
  memory:

limits:
  cpu:
  memory:
