appName: tapeevents
environment: prod
replicaCount: 1
loadBalancerIP: 20.228.250.146
image:
  name: multitenantacrprod.azurecr.io/tapeevents
  tag: "latest"
  port: 9002

requests:
  cpu:
  memory:

limits:
  cpu:
  memory: