appName: filter
environment: dev2
replicaCount: 20
loadBalancerIP: 20.25.13.117
image:
  name: multitenantdev2.azurecr.io/filter
  tag: "latest"
  port: 8098

requests:
  cpu: 200m
  memory: 256Mi

limits:
  cpu: 500m
  memory: 512Mi