name: Update Helm Repo
on:
  push:
    branches: [ main ]
    paths:
      - charts/**

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Chart Checkout
        uses: actions/checkout@v2
      - name: Install Helm
        uses: azure/setup-helm@1.1
        with:
          version: v3.11.0
      - name: Helm Repository Checkout
        uses: actions/checkout@v2
        with:
          repository: Trackonomy/helm-chart-repo
          ssh-key: ${{ secrets.REPO_SSH_KEY }}
          fetch-depth: 0
          ref: main
          path: helm-chart-repo
      - name: Helm Package
        run: |
          cd charts
          find . -maxdepth 1 -type d \(! -name . \) -exec bash -c "cd '{}' && helm package '{}' -d ../../helm-chart-repo"
      - name: Helm Push
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          cd ../helm-chart-repo
          git add .
          git commit -m "Loaded new charts"
          git push origin main